### ISSUE TITLE
Revit model download in documentation

### ISSUE THREAD

**Issue by lfcastel** [CircularEcoBIM/CircularityTool4Revit#6]
Is it possible to get the Revit model as shown in the documentation as a download link? In this way I can check if it runs correctly

**Comment by atomczak** [comment]
Sorry, Louis, that was part of the project's IP, and I no longer have access to the model with those values. And no longer have that Revit version. Next time we should do that based on IFC input ;)

But the tool should work on any input Revit model, given it doesn't have nested groups (as you can't override individual properties) and that you load those shared parameters from this repo. Let me know if you run into issues.

**Comment by lfcastel** [comment]
Allright, no worries, thanks!
